README.md
=> fixes link to GitHub Actions secrets

test-workflow.yml
=> feat: Add assume-role integ-test

README.md
adds tags to code blocks for better colors 🤷🏻‍♀️
=> docs: add code block tags

index.js, index.test.js
Fixes: #77 
This change  makes it so the regular expression also matches commas
=> fix: add comma to set of special characters

package.json
Update test in package.json to use specified linter.
=> chore: update package.json test to use linter

README.md
Addresses https://github.com/aws-actions/configure-aws-credentials/issues/113
=> chore: Add note about use with aws-cli to README

index.js
> By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.
Yeppers!
=> chore: Fix typo in README

README.md
*Issue #, if available:* none
*Description of changes:* correcting a typological error
=> Fix typo "charcters" in README.md

README.md, index.js, index.test.js
Reverted the update to the new GH API.
=> fix: reverting update to use new API

.github/ISSUE_TEMPLATE/bug-report.yml, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/documentation.yml, .github/ISSUE_TEMPLATE/feature-request.yml, .github/PULL_REQUEST_TEMPLATE.md, .github/workflows/close-stale-issues.yml, .github/workflows/closed-issue-message.yml
Adds issue templates and stale issue / closed issue message actions
=> chore: add issue templates and actions

.github/dependabot.yml, .mergify.yml, README.md
Adds a section at top of readme about new branch for visibility. Also makes automation changes on the base branch
---
=> chore: announce v1-node16 branch and update automation

dist/cleanup/index.js, package-lock.json, package.json
Avoid deprecation warnings on `npm install`
=> chore: update to @vercel/ncc

README.md, action.yml, index.js, index.test.js, package-lock.json, package.json
fixes #222
Implement proxy usage feature.
See here: https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/node-configuring-proxies.html
=> Feat: proxy implementation

README.md
Tiny change to the sample CloudFormation template to include an audience test in the role conditions.  Seems like a better practice to include it. The sample in the [github docs](https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-amazon-web-services#configuring-the-role-and-trust-policy) includes this condition.
---
* [*] Have you followed the guidelines in our [Contributing guide?](https://github.com/aws-actions/configure-aws-credentials/blob/master/CONTRIBUTING.md)
=> Minor: include a role condition test for AUD in sample CFN template

README.md
*Description of changes:* Update all the README example to use the new v2 version.
---
=> Update README examples to use v2

README.md
=> docs: clarify safety of version migration in readme

README.md
=> docs: add note about case sensivity to CloudFormation template

README.md
*Description of changes:* Just updating the documentation. This is the only place with v1 instead of v2.
---
=> Update README.md with v2 instead of v1

CHANGELOG.md
Updates changelog for newest release
---
=> chore: update changelog for v2.1.0

CHANGELOG.md
* `inline-session-policy` prop enables assuming a role with inline session policies ([d00f6c6](https://github.com/aws-actions/configure-aws-credentials/commit/d00f6c6f41fde02a9fd0d469040be6ed0df69e73))
* `managed-session-policies` prop enables assuming a role with managed policy arns ([d00f6c6](https://github.com/aws-actions/configure-aws-credentials/commit/d00f6c6f41fde02a9fd0d469040be6ed0df69e73))
---
=> chore: update changelog for release v2.2.0

README.md
Addresses new issues recently raised in #357 
---
=> chore: update readme with new thumbprint

.github/workflows/development.yml, src/CredentialsClient.ts, src/assumeRole.ts, src/helpers.ts, src/index.ts, test/helpers.test.ts, test/index.test.ts
Changes from linter and for unit tests
---
=> chore: vnext unit tests

README.md, action.yml, src/assumeRole.ts, src/helpers.ts, src/index.ts, test/index.test.ts
Fixes #793 
Fixes #599 
Adds a config option for handling special characters. If set, will retry fetching credentials until keys without special characters are returned.
=> feat: add config option for special character handling

.github/workflows/package.yml, test/index.test.ts
=> chore: fix packaging workflow

CHANGELOG.md
Update changelog for release
---
=> chore: release v3.0.2

CHANGELOG.md, README.md
*Description of changes:* Release v4.0.1
---
=> chore: release v4.0.1

src/assumeRole.ts
*Issue #, if available:* https://github.com/aws-actions/configure-aws-credentials/pull/925
*Description of changes:* Update code to address ESLint issues so that unit tests will pass.
---
=> fix: Address ESLint issues to fix unit tests

CHANGELOG.md
*Issue #, if available:* https://github.com/aws-actions/configure-aws-credentials/issues/1001
*Description of changes:* Add 4.0.2 changelog entry
---
* [ x ] Have you followed the guidelines in our [Contributing guide?](https://github.com/aws-actions/configure-aws-credentials/blob/main/CONTRIBUTING.md)
=> chore: add 4.0.2 entry

package-lock.json, package.json, test/index.test.ts
Fix unit test compat with AWS SDK JS v3.515.0
---
=> chore: fix test compatibility with AWS SDK v3.515.0

.github/workflows/tests-unit.yml
node deprecated and checkout repository version changed, using the deprecated node version..
---
=> chore: Update tests-unit.yml

.github/workflows/package.yml
Changing the checkout v3 to v4, it is basically a fix which was causing the deprecated issue.
*Issue #, if available:* fix
---
=> chore: Update package.yml

.github/workflows/release-please.yml, .release-please-manifest.json, package.json, release-please-config.json
release-please action integrated to automate releases. 
=> feat: added release-please action config

.github/workflows/automerge-approved-prs.yml, .github/workflows/dependabot-autoapprove.yml
=> fix: Dependabot autoapprove

.github/workflows/automerge-approved-prs.yml, .github/workflows/dependabot-autoapprove.yml
=> fix: Dependabot autoapprove id-token write permission

.github/workflows/automerge-approved-prs.yml, .github/workflows/dependabot-autoapprove.yml, .github/workflows/package-dist.yml, .github/workflows/release-please.yml
=> chore: update workflow file ARNs

README.md
N/A
Some examples in the doc had version v4 and some had v4.1.0. Updated the version in the docs to align with the latest release, v4.2.1
---
=> fix(docs): readme samples versioning

src/helpers.ts
=> fix: properly set proxy environment variable

.github/workflows/tests-integ-release.yml
Removed Windows from the OS matrix in the workflow.
=> chore: update OS matrix in inline-policy for tests-integ-release.yml

README.md
N/A
Bumps version used in README to v5.0.0
---
=> chore: update readme version to v5.0.0
