aws-actions/configure-aws-credentials

.gitignore
action.yml
index.js
index.test.js

As a security-conscious developer, long-lived credentials make me nervous, especially when I do not have a mechanism for an automated actor to change or delete them. Ideally, I would like to constantly refresh the GitHub Secrets that hold my AWS credentials with constantly rotating, short-lived, IAM Role credentials. Unfortunately, until GitHub adds an API for Secrets I cannot do that.
As a halfway measure, I would like to be able to set long-lived credentials in my GitHub Secrets that only have the permissions to assume short-lived credentials with wider permissions. The purpose of this PR is to enable this use-case.

feat: add support for assuming a role

---

index.js
index.test.js

It's super cool that this action now supports assuming a role (#17), it prompted me to start using it instead of a custom solution.
One thing I think was overlooked is that now if you assume a role, the temporary role credentials will be in plain text in Github Actions logs. Even if they're short-lived, they're still normally powerful and I think it's better if they're masked.
This PR marks the AWS credentials from an assumed role as secrets (access key id, secret access key and session token), which will mask them in the logs. This isn't an issue using AWS credentials straight from Github Actions secrets because of course they are already marked as secrets and hence are already masked.
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this …

fix: set role credentials as secrets to mask them in logs

---

README.md
index.js
index.test.js

Closes #18 
Ensure that alls tags applied to the AWS role session are valid.
For `GITHUB_ACTOR`, `[` and `]` must be removed.
For `GITHUB_WORKFLOW` I've inverted the [tag value requirement regex](https://docs.aws.amazon.com/STS/latest/APIReference/API_Tag.html), `[\p{L}\p{Z}\p{N}_.:/=+\-@]+`, and replaced any characters that don't conform. I've also truncated the value as it has a maximum of 256 chars.

fix: sanitize AWS session tags

---

index.js
index.test.js

Tags must conform to the pattern `[\p{L}\p{Z}\p{N}_.:/=+\-@]*`, so replacing with `*` isn't sufficient for sanitization.
I think underscore should work fine.

fix: change sanitization character from '*' to '_' for assume role tags

---

README.md
action.yml
index.js
index.test.js

Hi, 
I submit this PR for an ability to configure role session name after assuming a role with `configure-aws-credentials` Actions.
The story behind this PR is, recently, AWS has released a new feature for IAM - "CalledVia." It's a cool feature and no need to give extra write permissions to people to create stacks with CloudFormation. Now, we are changing our way of working by integrating GitHub Actions to deploy CloudFormation templates, but also want to know who update templates by using AWS CloudTrail. 
We figure out the CloudTrail will take session name as user name. Therefore we want to have a configurable session name to tag meaningful information on it instead of GitHubActions.

feat: Have an ability to configure session name

---

README.md
action.yml
index.js
index.test.js

feat: Add option to provide external ID

---

index.js
index.test.js

feat: infer role ARN if given role name

---

index.js
index.test.js

fix: mask both source and role credentials

---

README.md

chore: Update docs around AssumeRole permissions

---

README.md
action.yml
index.js
index.test.js

feat: don't require access key credentials for self-hosted runners

---

index.js
index.test.js

Related to #43 
Use a fairly permissive regex to check if the given region could feasibly be a valid region string.  Whether it is actually a valid region will be checked when `https://sts.$region.amazonaws.com` is called to get the account ID.

fix: validate region input string

---

index.js

fix: let the AWS SDK determine the STS regional endpoint

---

README.md
index.js
index.test.js

Related to #57, also document how to use different AWS accounts in the readme
This change is only necessary where the first action requires a session token, but the second action doesn't. For example:
```
- name: Configure AWS credentials from Production account
uses: aws-actions/configure-aws-credentials@v1
with:
aws-access-key-id: ${{ secrets.TEST_AWS_ACCESS_KEY_ID }}
aws-secret-access-key: ${{ secrets.TEST_AWS_SECRET_ACCESS_KEY }}
role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
aws-region: us-west-2
- name: Configure AWS credentials from Production account
uses: aws-actions/configure-aws-credentials@v1
with:
aws-access-key-id: ${{ secrets.PROD_AWS_ACCESS_KEY_ID }}
aws-secret-access-key: ${{ secrets.PROD_AWS_SECRET_ACCESS_KEY }}
aws-region: us-west-2
```
By submitting this pull …

fix: clear session token env var if present for non-session credentials

---

test-workflow.yml

Tests the scenario described in #57
This test currently fails in the same way as described in the issue:
https://github.com/clareliguori/configure-aws-credentials/runs/721375145

feat: Test repeated assume-role

---

index.js
index.test.js

Fixes #57 
Successful actions run:
https://github.com/clareliguori/configure-aws-credentials/runs/722182739?check_suite_focus=true

feat: Refresh and validate credentials after setting env var creds

---

README.md
action.yml
index.js
index.test.js

Fixes #81
Description of changes: fix to make tagging optional and improved code coverage

fix: Make tagging optional

---

action.yml
cleanup.js
cleanup.test.js
index.test.js
package.json

GitHub Actions can have a 'cleanup' step that runs at the end of the job.  The 'post' step for each action appears in the workflow run as an additional step at the end of each workflow job, in reverse order from the main steps.
Example:
https://github.com/clareliguori/configure-aws-credentials/runs/921351075?check_suite_focus=true

feat: Add post-job action cleanup of credentials and region env vars

---

index.js
index.test.js

Ensuring assume-role response is masked from debug output. Previously, response elements could be logged in the case where debugging was turned on. 
--

fix: Mask assume role response in debug output

---

index.js
index.test.js

Fixes #80
Certain workflows don't set a GITHUB_REF variable, because the triggering event doesn't have a branch or tag, so this PR makes GITHUB_REF optional. This changes the ordering of tags in tests since the Branch tag is now added at the end. It also adds two tests to validate this behavior, although I'm not convinced they provide much value.

fix: make GITHUB_REF env var optional

---

README.md

Update README.
I nearly gave up, believing it is not supported, until I read the action.yml. I think it is worth making this clear already in the README.

Readme: clarify that aws-session-token supported

---

index.js
index.test.js

This PR fix the issue #199
Description of changes:
This issue was occurring due to incorrect data type of the `role-skip-session-tagging` parameter.
In order to fix this issue need to type caste the value of the `role-skip-session-tagging `parameter from string to boolean.
when `role-skip-session-tagging` is false
when `role-skip-session-tagging` is true

fix: skips session tagging

---

README.md
action.yml
index.js
index.test.js

*Issue #, if available:* : 
https://github.com/aws-actions/configure-aws-credentials/issues/124
I would like to be able to use a github action to consume a web identity token file on an EKS worker node.  I have a self-hosted runner which does not run as `root` and thus it does not automatically get IRSA credentials, so my current workaround is to use a bash script which handles the assume role portions, but it doesn't neatly export the credentials the way this workflow does.  This pull request would allow users of this workflow to consume the web identity token file when assuming a role in a much cleaner fashion.

feat: Add the ability to use a web identity token file

---

README.md
index.js
index.test.js
package-lock.json
package.json

Added the ability to use GitHub provided OIDC token. If a user supplies a Role Arn and doesn't supply either an Access Key Id or a WebIdentityTokenFile we will attempt to load the OIDC Token from the environment variable provided by GitHub. If the Environment variable isn't set (because this could be running in a self-hosted runner) then we will fall back to the default credential provider as previously outlined in the `README.md`.
Updated the `README.md` to remove most mentions of using IAM Users as we expect future users to rely on the OIDC implementation, but the IAM User use-case is still defined (it's just not highlighted any more in the documentation).
Thanks to @aidansteele for the reference implmentation.
By submitting this pull request, I confirm that …

feat: added OIDC

---

README.md
index.js
index.test.js
package-lock.json
package.json

- Updated the OIDC JWT fetching process to use the new API
- replaced `sigstore` with `sts.amazon.aws` as the audience to reflect OIDC best practices for the audience to reflect the party that will be receiving the JWT.

fix: Updated token retrieval to use new API

---

README.md
index.js
index.test.js

- Updated to new GH OIDC API
- Used the `GITHUB_ACTIONS` environment variable to check if we're in a self-hosted runner or not (this appears to be teh [recommended practice](https://docs.github.com/en/actions/learn-github-actions/environment-variables#default-environment-variables) from GH) instead of guessing based on other set/un-set env variables
- Updated Readme with new OIDC Audiences.
- Tested this by running the action from [my fork](https://github.com/richardhboyd/my-sample-application/runs/3828996897?check_suite_focus=true)

upgraded to new GH OIDC API

---

.mergify.yml

Mergify deprecated strict mode in order to specify different conditions to get the PR in the queue and to get it merged. In order to solve this breaking change we will be changing mergify logic to have new queue_rules one as default for CI success and another for automated dependabot merges. Please follow the [link](https://blog.mergify.com/strict-mode-deprecation/) for more information.

fix: Strict Mode Deprecation

---

index.js
index.test.js

This PR fixes the issue #299 
Description - When multiple workflows try to assume a role at the same time then OIDC provider returns an error - `Couldn't retrieve verification key from your identity provider, please reference AssumeRoleWithWebIdentity documentation for requirements`
We now have a fix which will make sure that these parallel requests will retry assuming a role if it fails to do so. `retryAndBackoff` logic will take care of retrial of assuming a role at random times so that no 2 parallel requests will try to get credentials from OIDC provider at the same time. 
Screenshots - 
We have tried running 40 parallel workflows and all of them were able to assume a role successfully

fix: OIDC Parallel Requests error

---

README.md

The recommendation to hard code this in cloudformation doesn't seem very good. This is going to break every few months when github rotates their cert. Are there any AWS best practices around this. Just updating it in cloudformation and re-deploying isn't going to cut it if your cloudformation file is itself deployed via github actions...
EDIT: GitHub have confirmed the new hash, validating this change - https://github.blog/changelog/2022-01-13-github-actions-update-on-oidc-based-deployments-to-aws/.

fix: Update `token.actions.githubusercontent.com` thumbprint

---

README.md
action.yml
index.js

Allow the audience to be configured instead of defaulting to 'sts.amazonaws.com'.
It's desirable to be able to use different audiences to ensure that changes aren't enabled on the wrong location -- for example, you can use an audience of 'prod' in the production accounts and 'dev' in the development accounts.
By adding audience as an argument to the job, you can set a specific parameter in the with block, and the example has been updated to reflect this.
By the way, it's possible to configure both the role and the OICD provider with an 'either' clause, so you can use one of several audiences  -- but that somewhat defeats the point of using a non-default value :)
"Action": "sts:AssumeRoleWithWebIdentity",
"Condition": {
"StringLike": {
"token.actions.githubusercontent.com:sub": …

feat: Allow audience to be explicitly specified

---

index.js
index.test.js

temporary fix for: #103 
When a session token provided, use 1hr as role duration Otherwise, use the max duration of GitHub action (6hr)
---

fix: change role duration behavior

---

README.md
action.yml

https://github.com/aws-actions/configure-aws-credentials/blob/67fbcbb121271f7775d2e7715933280b06314838/index.js#L10
https://github.com/aws-actions/configure-aws-credentials/blob/67fbcbb121271f7775d2e7715933280b06314838/index.js#L315
update the actions.yml default description to refect the proper value when using oidc

chore: update role duration description

---

.github/dependabot.yml
.mergify.yml
action.yml

Issue #, if available: #489
Description of changes: Node 12 is EOL and we need to move to a more modern version. A comprehensive release is set for a new major version of this action which will use the most up to date version of node, but for now customers are getting warnings about Node 12 actions on GitHub. This is a temporary fix that will bump the runs to Node 16 while we work on v2.
---

fix: temporarily bump node version to 16

---

.github/workflows/package.yml

*Issue #, if available:* #531
*Description of changes:* Overhauls the package action to pull a token from AWS and use that token to push changes back to master. The token that's pulled from AWS has permission to bypass branch protection rules.
---

Packaging fix

---

.github/workflows/package.yml

The tests fail if there are credentials available in the env, so we need to get the AWS credentials *after* the package step.
---

fix: packaging test failure

---

README.md

* Closes #304 
Adds an example that explains how to use the `mask-aws-account-id` input option and its default.
---

feat: document mask-aws-account-id input

---

README.md
action.yml
index.js

Description of changes:
Adds boolean input option `role-chaining` which, when true, uses existing credentials in the environment to assume a role.
---
* [✅] Have you followed the guidelines in our [Contributing guide?](https://github.com/aws-actions/configure-aws-credentials/blob/main/CONTRIBUTING.md)

Add role-chaining support

---

README.md
action.yml
index.js
index.test.js

*Issue #229, if available:*
- Allows inline and managed session policies as inputs.
- Regenerated the `dist/` files.
- Added test.
- Some relevant docs:
- [AssumeRole](https://docs.aws.amazon.com/STS/latest/APIReference/API_AssumeRole.html#API_AssumeRole_RequestParameters)
- [AssumeRole AWS SDK](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/STS.html#assumeRole-property)
- [AssumeRoleWithWebIdentity](https://docs.aws.amazon.com/STS/latest/APIReference/API_AssumeRoleWithWebIdentity.html) 
- [AssumeRoleWithWebIdentity AWS SDK](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/STS.html#assumeRoleWithWebIdentity-property) 
---
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms …

Allow inline session policies for assuming role

---

README.md

As it turns out, it's very tedious to copy and paste the CF template into the designer all the time. So I added a cloudfront link to the template.

chore: add link to CF template in README

---

.github/workflows/tests-integ.yml
README.md
dist/index.js
src/index.ts
test/index.test.ts

fixes: #792 
If this configuration is used, a message will print in your workflow checking if you want to use OIDC. You can safely ignore this message
---

fix: action fails when intending to use existing credentials

---

README.md

https://docs.aws.amazon.com/accounts/latest/reference/manage-acct-identifiers.html
>While account IDs, like any identifying information, should be used and shared carefully, they are not considered secret, sensitive, or confidential information.
Given the above, I fix README as "AWS does **not** consider account IDs as sensitive information" is correct.
---

fix: Fix NEWS in README

---

README.md

Small typo that caused a major headache
*Issue #, if available:* Incorrect audience in readme
*Description of changes:* Corrects the audience displayed in readme
---

chore: change sts.amazon.com to sts.amazonaws.com in README.md

---

.github/workflows/close-stale-issues.yml

This somehow got removed in the migration to v3
---

chore: add stale issue bot

---

.github/workflows/tests-integ.yml
dist/index.js
src/index.ts
test/index.test.ts

fixes: #817 fixes: #819
If we aren't sure what the user is trying to do, validate credentials and export account ID anyway. The check in place was too strict and didn't consider cases like instance roles
---

fix: validation logic throwing unwanted errors

---

README.md
THIRD-PARTY
dist/index.js
src/assumeRole.ts
test/index.test.ts

*Issue #, if available:* N/A
*Description of changes:* We should recommend that customers use [OpenID Connect](https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-amazon-web-services) to authenticate instead of long-term credentials
---

feat: Recommending using OIDC

---

README.md

Fixes #877 Link to details on Assuming a Role goes nowhere
Fixes #877 
Change the link for readers to find more details on Assuming a Role.
The link was changed for  https://github.com/aws-actions/configure-aws-credentials#OIDC as suggested by @peterwoodworth in the issue.
---

chore: update link in docs

---

README.md

*Issue #, if available:* https://github.com/aws-actions/configure-aws-credentials/issues/906
*Description of changes:* Replace `tokens.actions.githubusercontent.com` with `token.actions.githubusercontent.com`
---

chore: fix provider URL in README

---

dist/index.js
src/assumeRole.ts
test/index.test.ts

*Description of changes:* Replace shortened URL with full URL. We don't want to link to external third-party link modifiers that might be changed or discontinued.
---

chore: replace shortened URL with full URL

---

README.md

*Description of changes:* In the example of using for AWS China the Role's ARN should also reflect the China partition.
---

chore: Update example ARN of China Role

---

.github/workflows/close-stale-issues.yml
.github/workflows/package.yml
.github/workflows/pull-request-lint.yml
.github/workflows/tests-integ.yml
examples/cfn-deploy-example/.github/workflows/compliance.yml
examples/cfn-deploy-example/.github/workflows/deploy.yml

Updated GitHub actions versions (e.g. `actions/checkout@v3` -> `actions/checkout@v4`). I checked and it seemed like there were no breaking changes. However, I was not able to actually run the updated workflows.
---

chore(deps): update github actions versions

---

.github/workflows/automerge-approved-prs.yml

The automerge-approved-prs workflow was getting skipped. I corrected a few syntax errors, and now it *should* work.
---

fix: automerge action syntax

---

README.md
action.yml
src/helpers.ts
src/index.ts
test/index.test.ts
test/mockinputs.test.ts

*Issue #, if available:* 
#1288
Adds a new config option, use-existing-credentials. When set, the action will attempt to re-use existing credentials instead of fetching new credentials. If there are no existing credentials (or if the existing credentials are no longer valid), the action will proceed as normal.
---

feat: idempotent fetch

---

.github/workflows/dependabot-autoapprove.yml
package.json

tries to run build as part of the tests to make sure that everything actually builds.
also, changes the dependabot-autoapprove action so that it should work.
---

fix: make sure action builds, also fix dependabot autoapprove

---

README.md

*Issue #, if available:* #1324
Documents the acceptable range of values for role-duration-seconds (according to STS documentation https://docs.aws.amazon.com/STS/latest/APIReference/API_AssumeRoleWithSAML.html).
---

feat: Document role-duration-seconds range

---

README.md
dist/cleanup/index.js
dist/index.js
src/helpers.ts
test/helpers.test.ts

*Issue #, if available:* #1320
*Description of changes:* Outputs the expiration field returned by the AssumeRole call as an additional GitHub output when the `output-credentials` flag is set. Could be useful for refreshing temporary credentials when they expire.
---

feat: Output expiration

---

src/helpers.ts

*Issue #, if available:* #1339
We now consider environment variables as inputs, which breaks the inputs if this action has already put out environment variable, which you do on multiple runs. This commit excludes the three AWS credentials environment variable, restoring the previous behavior.
Closes #1339.

fix: role chaning on mulitple runs

---

dist/cleanup/index.js
dist/index.js
src/helpers.ts

*Issue #1354*
This PR fixes an issue where environment variables from previous action runs were overriding explicitly provided inputs when the action is called multiple times in a workflow.
Modified translateEnvVariables() to only set input variables if they haven't already been set by GitHub Actions from the with: parameters.
---

fix: ensure explicit inputs take precedence over environment variables

---

README.md

This is a fix instead of a chore to force a 4.3.1 tag
Release-as: 4.3.1

fix: update readme to 4.3.1
